// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs audio-trim`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "audio-silence-remover",
    "icon": "🔊",
    "name": {
      "en": "Remove Silence",
      "ja": "無音をカット",
      "zh": "去除静音",
      "de": "Stille entfernen",
      "es": "Quitar silencios"
    },
    "desc": {
      "en": "Cut silent gaps out of an audio file.",
      "ja": "音声ファイルから無音部分を取り除きます。",
      "zh": "剪掉音频里的静音片段。",
      "de": "Stille Passagen aus einer Audiodatei herausschneiden.",
      "es": "Corta los tramos en silencio de un archivo de audio."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'audio-trim';
